2020-06-03 22:23:20 [scrapy] DEBUG: Crawled (200) <GET https://www.yelp.com/> (referer: None)
2020-06-03 22:23:46 [scrapy] DEBUG: Crawled (200) <GET https://www.yelp.com/search?find_desc=Thai&find_loc=San+Diego%2C+CA&ns=1> (referer: https://www.yelp.com/)
2020-06-03 22:24:09 [scrapy] DEBUG: Crawled (200) <GET https://www.yelp.com/search?find_desc=Thai&find_loc=San%20Diego%2C%20CA&start=30> (referer: https://www.yelp.com/search?find_desc=Thai&find_loc=San+Diego%2C+CA&ns=1)
2020-06-03 22:24:33 [scrapy] ERROR: Spider error processing <GET https://www.yelp.com/search?find_desc=Thai&find_loc=San%20Diego%2C%20CA&start=30> (referer: https://www.yelp.com/search?find_desc=Thai&find_loc=San+Diego%2C+CA&ns=1)
Traceback (most recent call last):
  File "f:\web scrapping\yelp\venv\lib\site-packages\scrapy\utils\defer.py", line 117, in iter_errback
    yield next(it)
  File "f:\web scrapping\yelp\venv\lib\site-packages\scrapy\utils\python.py", line 345, in __next__
    return next(self.data)
  File "f:\web scrapping\yelp\venv\lib\site-packages\scrapy\utils\python.py", line 345, in __next__
    return next(self.data)
  File "f:\web scrapping\yelp\venv\lib\site-packages\scrapy\core\spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "f:\web scrapping\yelp\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "f:\web scrapping\yelp\venv\lib\site-packages\scrapy\core\spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "f:\web scrapping\yelp\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 338, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "f:\web scrapping\yelp\venv\lib\site-packages\scrapy\core\spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "f:\web scrapping\yelp\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "f:\web scrapping\yelp\venv\lib\site-packages\scrapy\core\spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "f:\web scrapping\yelp\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "f:\web scrapping\yelp\venv\lib\site-packages\scrapy\core\spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "F:\web scrapping\yelpsecondinput\yelpdetails\yelpdetails\spiders\yelpspider.py", line 72, in numberofpages
    html = driver.page_source
  File "f:\web scrapping\yelp\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 679, in page_source
    return self.execute(Command.GET_PAGE_SOURCE)['value']
  File "f:\web scrapping\yelp\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "f:\web scrapping\yelp\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=83.0.4103.61)

2020-06-03 22:24:45 [scrapy] INFO: Closing spider (finished)
2020-06-03 22:24:47 [scrapy] INFO: Dumping Scrapy stats:
{'downloader/response_bytes': 3108845,
 'downloader/response_count': 3,
 'downloader/response_status_count/200': 3,
 'elapsed_time_seconds': 90.278185,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2020, 6, 3, 16, 54, 45, 569484),
 'httpcache/firsthand': 3,
 'httpcache/store': 3,
 'log_count/DEBUG': 171,
 'log_count/ERROR': 1,
 'log_count/INFO': 19,
 'request_depth_max': 2,
 'response_received_count': 3,
 'scheduler/dequeued': 3,
 'scheduler/dequeued/memory': 3,
 'scheduler/enqueued': 3,
 'scheduler/enqueued/memory': 3,
 'spider_exceptions/WebDriverException': 1,
 'start_time': datetime.datetime(2020, 6, 3, 16, 53, 15, 291299)}
2020-06-03 22:24:47 [scrapy] INFO: Spider closed (finished)
